e_cloud_finance/e_cloud_finance/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from e_cloud_finance_module import views
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings
from e_cloud_finance_module.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',views.index,name='index'),
    url(r'special/',views.special,name='special'),
    url(r'e_cloud_finance_module/',include('e_cloud_finance_module.urls')),
    url(r'logout/$', views.user_logout, name='logout'),
    url(r'^register/$',views.register,name='register'),
    url(r'user_login/$',views.user_login,name='user_login'),
     url(r"^static/(?P<path>.*)$",
        serve,
        {"document_root": settings.STATIC_ROOT},),
]

e_cloud_finance/e_cloud_finance_module/urls.py
from django.conf.urls import url
from e_cloud_finance_module import views
# SET THE NAMESPACE!
app_name = 'e_cloud_finance_module'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'user_login/$',views.user_login,name='user_login'),
     url(r'contacts/$',views.contacts,name='contacts'),
]

e_cloud_finance/e_cloud_finance_module/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	def __str__(self):
	  return self.user.username
class banking_details(models.Model):
	banke_name = models.OneToOneField(User,on_delete=models.CASCADE)
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	def __str__(self):
	  return self.user.username
class institution_income(models.Model):
	institution_name = models.OneToOneField(User,on_delete=models.CASCADE)
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	def __str__(self):
	  return self.user.username

e_cloud_finance/e_cloud_finance_module/forms.py
# from django import forms
# from e_cloud_finance_module.models import UserProfileInfo
# from django.contrib.auth.models import User
# class UserForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput())
#     class Meta():
#         model = User
#         fields = ('username','password','email')
# class UserProfileInfoForm(forms.ModelForm):
#      class Meta():
#          model = UserProfileInfo
#          fields = ('portfolio_site','profile_pic')

from django import forms
from e_cloud_finance_module.models import UserProfileInfo
from django.contrib.auth.models import User

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), required=False)

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')

e_cloud_finance/e_cloud_finance_module/views.py
# from django.shortcuts import render
from e_cloud_finance_module.forms import UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import *


def index(request):
    return render(request,'ecloud/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(HttpResponse):
    # if this is a POST request we need to process the form data
    return render(HttpResponse,'ecloud/registration.html')
    if HttpResponse.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(HttpResponse.POST)
        # check whether it's valid:
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(HttpResponse, template, {
                    'form': form,
                    'error_message': 'Username already exists.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Email already exists.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Passwords do not match.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.phone_number = form.cleaned_data['phone_number']
                user.save()
               
                # Login the user
                login(request, user)
               
                # redirect to accounts page:
                return HttpRedirect('register')

   # No post data availabe, let's just show the page.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'ecloud/login.html', {})

def contacts(request):
    return render(request,'ecloud/contacts.html')

e_cloud_finance/e_cloud_finance_module/templates/ecloud/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ecloud Finance</title>
   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body class="override">
    <nav class="navbar navbar-dark navbar-expand-md fixed-top bg-dark navbar-dark portfolio-navbar gradient">
      <div class="container">
        <ul class="nav navbar-nav">
{# E-cloud Home Link / Admin Link / Contact /About Link / Register Link#}
          <li><a href="{% url 'index' %}">ECLOUD Home</a></li>
          <li><a href="{% url 'admin:index' %}">Admin</a></li>
          <li><a href="{% url 'register' %}">About</a></li>
          <li><a href="{% url 'register' %}">Contact</a></li>
          <li><a href="{% url 'register' %}">Register</a></li>    
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/e_cloud_finance/">e_cloud_finance_module</a>
            </div>
           
        </div>
    </nav>
  
    <div class="container">
        <div class="row">
            {% block content %}

  <body class="container">
  <div class="container-fluid" style="margin-top: 30px">
    <div class="row-fluid">
      <div class="well" style="width: 320px; margin-left: auto; margin-right: auto">
        <div class="row-fluid">
          <div>
            {% block branding %}<h3 style="margin: 0 0 20px;">ECLOUD FINANCE</h3>{% endblock %}
          </div>
          <div class="form-actions-no-box">
            <a class="btn btn-primary js-tooltip" href="#" rel="nofollow" title="Ecloud login">Ecloud login</a>
          </div>
        </div><!-- /row fluid -->
      </div>
    </div>
  </div>
</body>



            {% endblock %}
        </div>
    </div>
   
    <footer>
        <div class="container">
            <div class="row well ml-t">
                <div class="col-lg-8 col-md-8">    
                    <h4>Developed by: <a href="https://josephdevs.duckdns.org" target="_blank">Joseph Njogu</a></h4>
                </div>
                <div class="col-lg-4 col-md-4">
                    <p class="m-t">Copyright &copy <a href="https://josephdevs.duckdns.org" target="_blank">www.josephdevs.duckdns.org</a> 2020</p>
                    <p>All Rights Reserved.</p>
                </div>
            </div>
        </div>
        
    </footer>
</body>
</html>

e_cloud_finance/e_cloud_finance_module/templates/ecloud/contacts.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
<head>
	<title>contacts</title>
</head>
<body>
<h1>contacts</h1>
<h1>To talk to us:</h1>
<form>
	Email<input type="email" name="email" required><br>
	Your Number:<input type="text" name="number" required><br>
	Comments here:
	<textarea placeholder="Leave a message to us:"></textarea>

	<input type="Submit" name="submit">




</form>
</body>
</html>

e_cloud_finance/e_cloud_finance_module/templates/ecloud/index.html
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

{% extends "ecloud/base.html" %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the E-cloud Finance !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

e_cloud_finance/e_cloud_finance_module/templates/ecloud/login.html
{% extends 'ecloud/base.html' %}
<!-- {% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'e_cloud_finance_module:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

{% extends "rest_framework/login_base.html" %}
{% load staticfiles %}
 -->
{% block style %}
    {% block bootstrap_theme %}
        <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css"
            type="text/css">
        <link rel="stylesheet" type="text/css" href="/static/login.css" />
    {% endblock bootstrap_theme %}
{% endblock %}

{% block title %}
    HealthCloud
{% endblock title %}

{% block body %}
<body>
    <div class="row">
    <div class="jumbotron">
  <h1><center>ECLOUD FINANCE LOGIN</center></h1>
</div>
<div class="col-xs-offset-3 col-xs-6">
        <form action="" role="form" method="post">
            {% csrf_token %}

            <div class="form-group {% if form.username.errors %}has-error{% endif %} form-group-lg">
                <label for="id_username">Email:</label>
                <input type="username" name="username" maxlength="100"
                    class="form-control"
                    id="id_username" required
                    {% if form.username.value %}
                        value="{{ form.username.value }}"
                    {% endif %}
                >
                {% if form.username.errors %}
                    <p class="text-error">
                        {{ form.username.errors|striptags }}
                    </p>
                {% endif %}
            </div>

            <div class="form-group {% if form.password.errors %}has-error{% endif %} form-group-lg">
                <label for="id_password">Password:</label>
                <input type="password" name="password" maxlength="100"
                    autocapitalize="off" autocorrect="off" class="form-control"
                    id="id_password" required>
                {% if form.password.errors %}
                    <p class="text-error">
                        {{ form.password.errors|striptags }}
                    </p>
                {% endif %}
            </div>

            <input type="hidden" name="next" value="{{ next }}" />

            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="well well-small text-error">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

            <input type="submit" name="submit" value="Log in" class="btn btn-primary form-control" id="submit-id-submit">
        </form>
        </div>
    </div>
</body>
{% endblock %}

e_cloud_finance/e_cloud_finance_module/templates/ecloud/registration.html
{% extends "ecloud/index.html" %}

{% block content %}
    <div class="container">
        <form  method="post">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Register</div>
                    <div class="panel-body">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                       
                        <div class="form-group clearfix">
                            <label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right">Username<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.email.id_for_label }}" class="col-md-4 control-label text-right">Email<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right">Password<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.password }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.password_repeat.id_for_label }}" class="col-md-4 control-label text-right">Confirm password:</label>
                            <div class="col-md-6">
                                {{ form.password_repeat }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.first_name.id_for_label }}" class="col-md-4 control-label text-right">First Name:</label>
                            <div class="col-md-6">
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.last_name.id_for_label }}" class="col-md-4 control-label text-right">Last Name:</label>
                            <div class="col-md-6">
                                {{ form.last_name }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.phone_number.id_for_label }}" class="col-md-4 control-label text-right">Phone Number:</label>
                            <div class="col-md-6">
                                {{ form.phone_number }}
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input type="submit" value="Register" class="btn btn-success">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}